INSERT INTO Areas VALUES (144, 'Αιγάλεω', 14)
INSERT INTO Areas VALUES (145, 'Πετρούπολη', 14)

INSERT INTO Parking VALUE ('144A', 'MetroParkit', 20 , 144 , 5 , '11:00:00' , '21:00:00', 'https://maps.app.goo.gl/L47Js6Wi4xEfti5y9')
INSERT INTO Parking VALUE ('144B', 'Παρκινγ Μιχαλης ', 60 , 144 , 4, '00:00:00', '00:00:00', 'https://maps.app.goo.gl/Sut3FW3qa6goCB3Q9')
INSERT INTO Parking VALUE ('144C', 'Egaleo Metro Park', 40 , 144 , 3,  '00:00:00', '00:00:00', 'https://maps.app.goo.gl/V9w9SLx7irtKEaT39')
INSERT INTO Parking VALUE ('144D', 'Tetris Parking', 30 , 144 , 3,  '00:00:00', '00:00:00' , 'https://maps.app.goo.gl/XZWoTxDyK2d57fZ76')
INSERT INTO Parking VALUE ('145A', 'Grove St.Demetrios', 60 , 145 , 5 ,  '00:00:00', '00:00:00' , 'https://maps.app.goo.gl/M6VkfAvDthF3yFAM8')
INSERT INTO Parking VALUE ('145B', 'Παρκινγ Πετρουπολη', 40 , 145 , 5 , '00:00:00', '00:00:00' , 'https://maps.app.goo.gl/uUCscGaLZGBnzH3E9')