INSERT INTO Areas VALUES(14,'Δυτικά Προάστια',1)
INSERT INTO Areas VALUES(142,'Περιστέρι',14)
INSERT INTO Areas VALUES(143,'Άγιοι Ανάργυροι',14)

INSERT INTO Parking VALUES('142A','Αισχύλου, Ρούσβελτ Φραγκλίνου &, Περιστέρι 121 34', 15,142, 5, '00:00:00', '24:00:00', 'https://maps.app.goo.gl/s7PabrGbk2LBzcyf7')
INSERT INTO Parking VALUES('142B', 'Ελ. Βενιζέλου 91, Περιστέρι 121 32', 50, 142,5,'00:00:00', '24:00:00' 'https://maps.app.goo.gl/jXpK4oCc9Eq2k1B46')

