    INSERT INTO Areas VALUES (117, 'Ελληνικό' , 11)
    INSERT INTO Areas VALUES (118, 'Γλυφάδα' , 11)
    INSERT INTO Areas VALUES (119, '΄Αλιμος' , 11)
    INSERT INTO Areas VALUES (1110, 'Αργυρούπολη', 11)
    INSERT INTO Areas VALUES (1111, 'Ηλιούπολη', 11)  
    
    
  
    INSERT INTO Parking VALUE ('117A', 'Ελευθεριου Βενιζελου 3', 35, 117, 7 , '09:00:00', '18:00:00', 'https://maps.app.goo.gl/8ptzonkVPSXLcTgP8' )
    INSERT INTO Parking VALUE ('118A', 'Παρκινγκ κύπρου', 40 , 118 , 6,  '09:00:00', '22:00:00', 'https://maps.app.goo.gl/eop6h3zSbEj2tghZ7')
    INSERT INTO Parking VALUE ('118B', 'Lazaraki Street Parking', 30 , 118, 5 , '09:00:00', '14:00:00', 'https://maps.app.goo.gl/YGETxVtoq9VSXynb6' )
    INSERT INTO Parking VALUE ('118C', 'Παρκινγκ Γλυφαδα', 25 , 118 , 9 ,  '00:00:00', '00:00:00', 'https://maps.app.goo.gl/iFpyn5m369fG6ueU6') 
    INSERT INTO Parking VALUE ('119A', 'Παρκινγ Μαρινας Αλιμου', 50, 119, 7,  '00:00:00', '00:00:00', 'https://maps.app.goo.gl/fq37TW9MsK8Foez96')
    INSERT INTO Parking VALUE ('119B', 'Παρκινγκ Αλιμος', 30, 119, 4 ,  '00:00:00', '00:00:00','https://maps.app.goo.gl/XAYtBDg1zCawSANz9')
    INSERT INTO Parking VALUE ('119C', 'Δημοτικο ΠΑρκινγ Αλιμου', 50, 119, 0 ,  '00:00:00', '00:00:00', 'https://maps.app.goo.gl/PFVpBNsh4Ty43exZ9' )
    INSERT INTO Parking VALUE ('1110A', 'Parking Lot Alexioupoleos', 40, 1110, 5 ,  '00:00:00', '00:00:00', 'https://maps.app.goo.gl/kYGnnDJvYXJjTLSd9')
    INSERT INTO Parking VALUE ('1111A', 'Παρκινγκ Ηλιουπολη', 35, 1111, '00:00:00', 5 , '00:00:00','https://maps.app.goo.gl/Gsn2xFPoLbZepGUp6')
    INSERT INTO Parking VALUE ('1111B', 'Παρκινγκ Γιωργος', 30, 1111, '00:00:00', 6, '00:00:00', 'https://maps.app.goo.gl/fgAdMWSMxY3Pua376')
    INSERT INTO Parking VALUE ('1111C', 'Municipal Parking', 40 , 1111, '00:00:00', 7 , '00:00:00', 'https://maps.app.goo.gl/nSuVg1W8z3miiJev5')
    